version: '3.8'

services:
  app:
    container_name: app
    build:
      context: .
      target: ${NODE_ENV}
    volumes:
      - ./src:/usr/src/app/src
      - nodemodules:/usr/src/app/node_modules
      - ./${LOG_DIRECTORY}:/usr/src/app/${LOG_DIRECTORY}
    ports:
      - ${PORT}:${PORT}
    command: npm run docker
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    networks:
      - app-network
    depends_on:
      - postgres
    restart: always
  
  postgres:
    container_name: postgres
    build:
      context: .
      dockerfile: Dockerfile.pg
    networks:
      - app-network
    env_file:
      - .env
    environment:
      PG_DATA: /var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - pgdata:/var/lib/postgresql/data
      - pglogs:/logs
    restart: always

networks:
  app-network:
    driver: bridge

volumes:
  pgdata:
  pglogs:
  nodemodules: {}