version: '3.0'

services:
  main:
    container_name: app
    build:
      context: .
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - ${PORT}:${PORT}
    command: npm run docker
    depends_on:
      - postgres
    restart: always
    networks:
      - app_network
  postgres:
    container_name: postgres
    build:
      context: .
      dockerfile: Dockerfile.pg
    env_file:
      - .env
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  pgdata:
